version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/fluttium_flow"
    schedule:
      interval: "daily"