name: fluttium_cli
description: The CLI for Fluttium.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.1.3
  pub_updater: ^0.2.1
  fluttium_flow:
    path: ../fluttium_flow
  meta: ^1.8.0
  mason: ^0.1.0-dev.33
  collection: ^1.16.0
  path: ^1.8.2
  watcher: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  fluttium: