name: fluttium_cli
description: The CLI for Fluttium, a UI testing framework for Flutter
homepage: https://fluttium.dev
repository: https://github.com/wolfenrain/fluttium
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  fluttium_flow:
    path: ../fluttium_flow
  fluttium_runner:
    path: ../fluttium_runner
  mason: ^0.1.0-dev.33
  mason_logger: ^0.1.3
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.2.1
  watcher: ^1.0.1
  yaml: ^3.1.1

dependency_overrides: 
  mason_logger:
    git: 
      url: https://github.com/felangel/mason
      ref: feat/make-choose-one-and-choose-any-mappable
      path: packages/mason_logger

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  fluttium: